### ISSUE TITLE
Telepads causing crashes in this modpack

### ISSUE THREAD

**Issue by ArtixAllMighty** [The-Nexus-Project/Limitless-4#2]
ArtixAllMighty/Telepads2016#54

it seems telepads causes crashes ? I tried debugging this in my dev environement, but I can't recreate the bug myself. 
If anyone else has input on the issue, highly likely a mod compat issue, I'll try and resolve it when I can pinpoint the issue !

The issue being that the BlockEntity for the Telepad isn't being found for the TelepadBlock.
A BE is initialized every time a block is placed down, and called for to be deleted when the block is broken

**Comment by Gbergz** [comment]
Hey, this ONLY happens on a server. Not singleplayer.

**Comment by ArtixAllMighty** [comment]
That makes the issue even weirder. the crash occurs when the game looks for the BE, which should be registered server side. if it wasn't, client wouldnt work.
the server does have the mod too right ?

**Comment by Gbergz** [comment]
Ofcourse!

**Comment by ArtixAllMighty** [comment]
I just tested the mod outside of dev, as sole mod installed, on a clean forge install, and i get no crashes and the mod works as intended. 
Can I ask of you to find out what mod is causing issues with the telepad mod ?

**Comment by Gbergz** [comment]
Not really that easy to find it out just like that. If you want you can help. Download the pack. Remove some mods. one by one. Gonna try when I have time.

**Comment by noncom** [comment]
So ok, I just tried to start a local server and join to it and build a Telepad... it worked. The telepads get built okay and I can teleport from one to another!

What I can think of: could this be a problem with the fact that the world is not a fresh one? Like, it migrated from modpack version 6 or something like this iirc. It should NOT be the cause of the problem because a `NoClassDefFoundError` error is not something you get when user data is wrong, it indicates a basic Java failure... but as of now my only theory is that either the error appears on worlds that have existed for quite a while already, or that it's somehow related to the world migration between modpack versions, but I totally have no idea how could that cause such a problem.

**Comment by noncom** [comment]
Well, I tried reproducing all the conditions we had when the crash happened: all the possible interactions with the other mods and stuff on our base: no effect, everything works perfectly.

If this bug is somehow related to the world being a bit old, then there's a very serious covert bug somewhere in Forge or Minecraft about how worlds are managed.

**Comment by ArtixAllMighty** [comment]
must have been a weird issue somewhere. 
I couldn't trace the issue back to the mod.
the game wasn't finding the block entity that is responsible for all logic behind the telepad. 
(for the general idea : furnaces have block entities too)

I'm glad it got resolved. it was probably, as stated, a weird world bug or issue that got somehow auto resolved.

**Comment by noncom** [comment]
Well, not sure it's actually resolved on the server. We never tried building another Telepad :D because if it crashes again, it's us stressing Gbergz again to help us fix that. We are suffering without Telepads but afraid to build them.

But after some thinking I can't definitely say that it's a Telepads issue, because I can't think of any way that it might have done something to cause a `NoClassDefFoundError` exception. It's likely a Forge/Minecraft/Java problem... but who knows... maybe it's some bytecode version incompatibility bug or something.

It would have been awesome if we could download the world and debug it locally in IDEA, but it's not possible because it's too big and BisectHosting has problems with that (which is the reason I would never host a Minecraft server there tbh).
